### ISSUE TITLE
duplicate repository

### ISSUE THREAD

**Issue by danielinux** [akanouras/pepsal#1]
Hi there! Thank you for using the proper software to import the repository from the old SVN.

We (the original authors) had the same idea, so we would kindly ask you to re-fork the project via github, so the SHA1 of our commits would be aligned again.

This will make your contribution more visible to the community and easier to merge later on.

You may simply hit the "Fork" button from
https://github.com/danielinux/pepsal

Thanks for considering this.

**Comment by akanouras** [comment]
Hello!
Sorry for not responding earlier; just saw this message.

I only created this repo so that it would be available for easy cloning by git(hub) users and will be happy to tear it down now that you have put up yours. 

In retrospect, I really should have contacted you before creating it, just as the reposurgeon docs suggest. I only felt that as researchers you had moved on to other subjects.

Thank you for your research and work on this subject!
